# Generated by Django 3.1.4 on 2020-12-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
